### ISSUE TITLE
Change default Aladin zoom level?

### ISSUE THREAD

**Issue by thespacedoctor** [genghisken/psat-server-web#7]
Would it be beneficial to change the default Aladin zoom level to closer match the angular size of the ATLAS stamps? I would make it easier to register equivalent sources quickly by eye.

Current it defaults to a FoV of 1.19'

[![](https://live.staticflickr.com/65535/51654588279_e8040e27ed_z.png)](https://live.staticflickr.com/65535/51654588279_e8040e27ed_o.png)

but a FoV of 4.83' is a closer match (not sure if it can be set to 5' programmatically)

[![](https://live.staticflickr.com/65535/51653917391_e038457250_z.png)](https://live.staticflickr.com/65535/51653917391_e038457250_o.png)

**Comment by genghisken** [comment]
Thanks for pointing this out! This is a bug caused by my merging of the Pan-STARRS & ATLAS web interface code. The original default zoom level on Aladin did originally match the ATLAS FOV.  (The default zoom level is at Pan-STARRS FOV at the moment!) I'll let you know when it's fixed, so leave this ticket open.

**Comment by genghisken** [comment]
Fixed.
